
spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/userTable
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  rsocket:
    server:
      port: ${PORT:5000}
